name: Daily Sign Bot

on:
  schedule:
    # UTC 23:00 = 北京时间 7:00
    - cron: '0 23 * * *'
  # 支持手动触发
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run sign script
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        run: python sign.py
